version: '3.8'
services:
  chia-init:
    image: ghcr.io/chia-network/chia:latest
    environment:
      CHIA_ROOT: /chia-data
      service: wallet
      self_hostname: 0.0.0.0
      keys: "persistent"
    volumes:
      - ~/.dig/chia-data:/chia-data
      - ~/.dig/chia_keys:/root/.chia_keys
    command: >
      /bin/sh -c "chia keys generate -l dig_node"

  chia-nodes:
    image: ghcr.io/chia-network/chia:latest
    depends_on:
      chia-init:
        condition: service_completed_successfully
    ports:
      - "8444:8444"
      - "8555:8555"
      - "8562:8562"
      - "8575:8575"
      - "9256:9256"
    environment:
      CHIA_ROOT: /chia-data
      service: data data_layer_http
      self_hostname: 0.0.0.0
      keys: "persistent"
    volumes:
      - ~/.dig/chia-data:/chia-data
      - ~/.dig/chia_keys:/root/.chia_keys

  dig-server:
    image: michaeltaylor3d/dig-server:latest
    depends_on:
      - chia-nodes
    ports:
      - "8080:8080"
      - "41410:41410"
    volumes:
      - ~/.dig/chia-data:/chia-data
      - ~/.dig/store-cache:/root/.dig/store-cache
    environment:
      - dig__FullNodeHost=chia-proxy.evergreenminer-prod.com
      - dig__FullNodePort=443
      - dig__WalletHost=chia-nodes
      - dig__WalletPort=9256
      - dig__DataLayerHost=chia-nodes
      - dig__DataLayerPort=8562
      - dig__DataLayerMirrorPort=8575
      - dig__DigPort=41410
      - dig__ChiaCertDirectory=/chia-data/config/ssl/
      - dig__ActAsCdn=false
      - CHIA_ROOT=/chia-data

networks:
  default:
    name: dig_network
